version: "3.8"

services:
  config-service:
    container_name: config-service
    image: vcchavez/config-service:latest
    restart: always
    ports:
      - "8081:8081"

  eureka-service:
    container_name: eureka-service
    image: vcchavez/eureka-service:latest
    restart: always
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    environment:
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
    hostname: eureka-service

  empleado-bd:
    container_name: empleado-bd
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: empleado
    volumes:
      - /var/lib/postgresql/data

  empleado-service:
    container_name: empleado-service
    image: vcchavez/empleado-service:latest
    restart: on-failure
    ports:
      - "8090:8090"
    depends_on:
    - empleado-bd
    - config-service
    - eureka-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - spring.config.fail-fast=true
      - spring.profiles.active=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://empleado-bd:5432/empleado
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - HOSTNAME=config-service
      - EUREKA=eureka-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  marcas-reloj-bd:
    container_name: marcas-reloj-bd
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: marcas-reloj
    volumes:
      - /var/lib/postgresql/data

  marcas-reloj-service:
    container_name: marcas-reloj-service
    image: vcchavez/marcas-reloj-service:latest
    restart: on-failure
    ports:
      - "8091:8091"
    depends_on:
    - marcas-reloj-bd
    - config-service
    - eureka-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - spring.config.fail-fast=true
      - spring.profiles.active=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://marcas-reloj-bd:5432/marcas-reloj
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - HOSTNAME=config-service
      - EUREKA=eureka-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  justificativo-bd:
    container_name: justificativo-bd
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: justificativos
    volumes:
      - /var/lib/postgresql/data

  justificativo-service:
    container_name: justificativo-service
    image: vcchavez/justificativo-service:latest
    restart: on-failure
    ports:
      - "8092:8092"
    depends_on:
    - justificativo-bd
    - config-service
    - eureka-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - spring.config.fail-fast=true
      - spring.profiles.active=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://justificativo-bd:5432/justificativos
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - HOSTNAME=config-service
      - EUREKA=eureka-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  autorizacion-bd:
    container_name: autorizacion-bd
    image: postgres:latest
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: autorizacion
    volumes:
      - /var/lib/postgresql/data

  autorizacion-service:
    container_name: autorizacion-service
    image: vcchavez/autorizacion-service:latest
    restart: on-failure
    ports:
      - "8093:8093"
    depends_on:
    - autorizacion-bd
    - config-service
    - eureka-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - spring.config.fail-fast=true
      - spring.profiles.active=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://autorizacion-bd:5432/autorizacion
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - HOSTNAME=config-service
      - EUREKA=eureka-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  sueldos-bd:
    container_name: sueldos-bd
    image: postgres:latest
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sueldos
    volumes:
      - /var/lib/postgresql/data

  sueldos-service:
    container_name: sueldos-service
    image: vcchavez/sueldos-service:latest
    restart: on-failure
    ports:
      - "8094:8094"
    depends_on:
    - sueldos-bd
    - config-service
    - eureka-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - spring.config.fail-fast=true
      - spring.profiles.active=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sueldos-bd:5432/sueldos
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - HOSTNAME=config-service
      - EUREKA=eureka-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  gateway-service:
    container_name: gateway-service
    image: vcchavez/gateway-service:latest
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - config-service
      - eureka-service
      - empleado-service
      - marca-reloj-service
      - justificativo-service
      - autorizacion-service
      - sueldos-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - HOSTNAME=config-service
      - EUREKA=eureka-service
      - spring.config.fail-fast=true
      - spring.profiles.active=default

  #frontend:
  #  container_name: frontend
  #  image: vcchavez/frontend:latest
  #  restart: on-failure
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - config-service
  #    - eureka-service
  #    - empleado-service
  #    - marca-reloj-service
  #    - justificativo-service
  #    - autorizacion-service
  #    - sueldos-service
  #    - gateway-service
  #  deploy:
  #    restart_policy:
  #      condition: on-failure


  