version: "3.8"

services:
  config-service:
    container_name: config-service
    image: vcchavez/config-service:latest
    restart: always
    ports:
      - "8081:8081"

  eureka-service:
    container_name: eureka-service
    image: vcchavez/eureka-service:latest
    restart: always
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    environment:
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081

  empleado-bd:
    container_name: empleado-bd
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: empleado
    volumes:
      - /var/lib/postgresql/data

  empleado-service:
    container_name: empleado-service
    image: vcchavez/empleado-service:latest
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - config-service
      - eureka-service
      - empleado-bd
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://empleado-bd:5432/empleado
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  gateway-service:
    container_name: gateway-service
    image: vcchavez/gateway-service:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - config-service
      - eureka-service
      - empleado-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
    links:
      - eureka-service

  