server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/empleado/**
        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/**
        - id: sueldos-service
          uri: lb://sueldos-service
          predicates:
            - Path=/sueldos/**
        - id: autorizacion-service
          uri: lb://autorizacion-service
          predicates:
            - Path=/autorizacion/**
        - id: marcas-reloj-service
          uri: lb://marcas-reloj-service
          predicates:
            - Path=/marcas-reloj/**
        