server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: git@github.com:Vanina11/tingeso2.git
          clone-on-start: true
          search-paths: config-data
  application:
    name: config-service
